version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: yearly
    timezone: Europe/London
  open-pull-requests-limit: 99
  ignore:
    - dependency-name: "AWSSDK.SQS"
      update-types: ["version-update:semver-patch"]
    - dependency-name: "Microsoft.AspNetCore.TestHost"
