dist: bionic
language: csharp
mono: none

os:
  - linux
  - osx

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - NUGET_XMLDOC_MODE=skip

branches:
  only:
    - master

cache:
  directories:
    - /home/travis/.nuget/packages

script:
  - ./build.sh

after_success:
  - bash <(curl -s https://codecov.io/bash) -f "./artifacts/coverage.netcoreapp3.1.cobertura.xml" -F $TRAVIS_OS_NAME || echo "Codecov did not collect coverage reports"
