os: Visual Studio 2019
version: 0.3.1.{build}

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_XMLDOC_MODE: skip

branches:
  only:
    - master

build_script:
  - ps: .\Build.ps1

after_build:
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - pip install codecov
  - codecov -f "artifacts\coverage.netcoreapp3.1.cobertura.xml" -F windows

artifacts:
  - path: artifacts\*.nupkg
  - path: artifacts\*.snupkg

nuget:
  disable_publish_on_pr: true

skip_tags: false
test: off

deploy:

  - provider: NuGet
    api_key:
      secure: 0mjb8vhWbGGoiUWJHX0qhUAEU5lrup9rEgEy/HBt5zpewF1suaBismyHHE53hTGu
    artifact: /.*\.*nupkg/
    skip_symbols: false
    on:
      appveyor_repo_tag: true
