<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Tests for MartinCostello.Testing.AwsLambdaTestServer.</Description>
    <OutputType>Exe</OutputType>
    <RootNamespace>MartinCostello.Testing.AwsLambdaTestServer</RootNamespace>
    <TargetFramework>net11.0</TargetFramework>
    <UseDefaultCodeAnalysisRuleSet>true</UseDefaultCodeAnalysisRuleSet>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.RuntimeSupport" />
    <PackageReference Include="Amazon.Lambda.Serialization.Json" />
    <PackageReference Include="AWSSDK.SQS" />
    <PackageReference Include="GitHubActionsTestLogger" />
    <PackageReference Include="MartinCostello.Logging.XUnit.v3" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="xunit.v3.mtp-v2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\AwsLambdaTestServer\MartinCostello.Testing.AwsLambdaTestServer.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <PropertyGroup>
    <CollectCoverage>true</CollectCoverage>
    <CoverageRunSettings>$(MSBuildThisFileDirectory)tests.runsettings</CoverageRunSettings>
    <Threshold>95,75,95</Threshold>
  </PropertyGroup>
</Project>
