name: CI_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  batch: true
  branches:
    include:
    - master
  tags:
    include:
    - v*

phases:
- template: build-template.yml
  parameters:
    agentOS: Linux
- template: build-template.yml
  parameters:
    agentOS: macOS
- template: build-template.yml
  parameters:
    agentOS: Windows
