parameters:
  agentOS: 'Windows'
  phaseName: ''
  queueName: ''
  buildArgs: ''
  beforeBuild: []
  afterBuild: []
  variables: {}
  dependsOn: ''

phases:
  - phase: ${{ coalesce(parameters.phaseName, parameters.agentOS) }}
    dependsOn: ${{ parameters.dependsOn }}
    displayName: ${{ coalesce(parameters.phaseName, parameters.agentOS) }}
    queue:
      ${{ if ne(parameters.queueName, '') }}:
        name: ${{ parameters.queueName }}
      ${{ if and(eq(parameters.queueName, ''), eq(parameters.agentOS, 'Linux')) }}:
        name: Hosted Ubuntu 1604
      ${{ if and(eq(parameters.queueName, ''), eq(parameters.agentOS, 'macOS')) }}:
        name: Hosted macOS
      ${{ if and(eq(parameters.queueName, ''), eq(parameters.agentOS, 'Windows')) }}:
        name: Hosted Windows 2019 with VS2019
    variables:
      AgentOSName: ${{ parameters.agentOS }}
      BuildArgs: ${{ parameters.buildArgs }}
      ${{ insert }}: ${{ parameters.variables }}
    steps:
      - ${{ parameters.beforeBuild }}
      - ${{ if eq(parameters.agentOS, 'Linux') }}:
        - script: |
            sudo apt-get update
            sudo apt-get install -y --no-install-recommends gettext libcurl4-openssl-dev libicu-dev libssl-dev libunwind8
          name: InstallDotNetCoreDeps
          displayName: Install .NET Core pre-requisites
      - ${{ if eq(parameters.agentOS, 'Windows') }}:
        - powershell: |
            .\Build.ps1 -OutputPath $(Build.StagingDirectory) $(BuildArgs)
          name: BuildAndTest
          displayName: Build and test
          env:
            DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
            NUGET_XMLDOC_MODE: skip
      - ${{ if ne(parameters.agentOS, 'Windows') }}:
        - script: |
            ./build.sh --output $(Build.StagingDirectory) $(BuildArgs)
          name: BuildAndTest
          displayName: Build and test
          env:
            DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
            NUGET_XMLDOC_MODE: skip
      - task: PublishTestResults@2
        name: PublishTests
        displayName: Publish test results
        condition: always()
        inputs:
          failTaskOnFailedTests: true
          testRunner: VSTest
          testRunTitle: Unit and integration tests ($(AgentOSName))
          testResultsFiles: $(Build.SourcesDirectory)/**/*.trx
      - task: PublishCodeCoverageResults@1
        name: PublishCodeCoverage
        displayName: Publish code coverage
        condition: always()
        inputs:
          codeCoverageTool: cobertura
          failIfCoverageEmpty: true
          reportDirectory: $(Build.StagingDirectory)/**/coverage
          summaryFileLocation: $(Build.StagingDirectory)/coverage.netcoreapp3.1.cobertura.xml
      - task: PublishBuildArtifacts@1
        displayName: Publish build artifacts
        condition: eq(variables['System.PullRequest.IsFork'], false)
        inputs:
          PathToPublish: '$(Build.StagingDirectory)'
          ArtifactType: Container
          ${{ if eq(parameters.artifacts.name, '') }}:
            ArtifactName: BuildDrop-$(AgentOSName)
          ${{ if ne(parameters.artifacts.name, '') }}:
            ArtifactName: ${{ parameters.artifacts.name }}
      - ${{ parameters.afterBuild }}
